# Numpy

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [1]:
import numpy as np

arr = np.loadtxt('minutes_n_ingredients.csv', delimiter=",", dtype=np.int32)
print(arr[0:5,:])
len(arr)

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


100000

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [2]:
print('Среднее по 2му столбцу: ', np.around(np.mean(arr[:,1])))
print('Среднее по 3му столбцу: ', np.around(np.mean(arr[:,2])))
print('Минимум по 2му столбцу: ', np.amin(arr[:,1]))
print('Минимум по 3му столбцу: ', np.amin(arr[:,2]))
print('Максимум по 2му столбцу: ', np.amax(arr[:,1]))
print('Максимум по 3му столбцу: ', np.amax(arr[:,2]))
print('Медиана по 2му столбцу: ', np.median(arr[:,1]))
print('Медиана по 3му столбцу: ', np.median(arr[:,2]))

Среднее по 2му столбцу:  21601.0
Среднее по 3му столбцу:  9.0
Минимум по 2му столбцу:  0
Минимум по 3му столбцу:  1
Максимум по 2му столбцу:  2147483647
Максимум по 3му столбцу:  39
Медиана по 2му столбцу:  40.0
Медиана по 3му столбцу:  9.0


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [3]:
q = np.quantile(arr[:,1], q = 0.75)
arr[:,1] = arr[:,1].clip(max = q)

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [4]:
zeros = len(arr[:,1])-np.count_nonzero(arr[:,1]) # Количество продолжительностей, равных нулю
print(zeros)
np.place(arr[:,1], arr[:,1] == 0, 1) # Замена на единицы

479


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [15]:
len(np.unique(arr, axis = 0))

100000

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [6]:
print(len(np.unique(arr[:,2])))
print(np.unique(arr[:,2]))

37
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [7]:
i5 = arr[(arr[:,2] < 5) | (arr[:,2] == 5)]
len(i5)

17262

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [8]:
m = np.divide(arr[:,2], arr[:,1])
np.amax(m)

24.0

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [9]:
arrCopy = arr[arr[:, 1].argsort()[::-1]] # Сортировка по убыванию продолжительности
srIn = arrCopy[0:100,:] # Топ-100
print('Cреднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью: ', np.mean(srIn[:,2]))

Cреднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью:  9.96


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [10]:
idx = np.random.randint(100000, size=10)
rows = arr[idx, :]
print(rows)

[[ 38946     65      8]
 [461674     65      9]
 [253080     40      9]
 [294273     65      6]
 [ 46397     65     12]
 [414992     50      7]
 [110790     65     18]
 [ 38762     16      8]
 [ 47492     30      7]
 [ 98290     60      7]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [11]:
k = len(arr[(arr[:,2] < (np.mean(arr[:,2])))])
k1 = k / len(arr) * 100
print(k1, '%', sep = '')

58.802%


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [12]:
s = np.zeros((100000, 1), dtype = np.int32)
arr = np.append(arr, s, 1)
np.place(arr[:,3], (((arr[:,1] < 20) | (arr[:,1] == 20)) & ((arr[:,2] < 5) | (arr[:,2] == 5))), 1)
arr

array([[127244,     60,     16,      0],
       [ 23891,     25,      7,      0],
       [ 94746,     10,      6,      0],
       ...,
       [498432,     65,     15,      0],
       [370915,      5,      4,      1],
       [ 81993,     65,     14,      0]])

13. Выведите процент "простых" рецептов в датасете

In [13]:
p = len(arr[(arr[:,3] == 1)])
p1 = p / len(arr) * 100
print(p1, '%', sep = '')

9.552%


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.